name: Build Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner for .exe

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.1'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt
        pip install pyinstaller  # Install PyInstaller

    - name: Package with PyInstaller
      run: |
        pyinstaller --onefile main.py --add-data "bin;bin"  # Adjust the command to include the /bin folder

    - name: Zip the artifacts
      run: |
        powershell Compress-Archive -Path dist\* -DestinationPath dist\executables.zip  # Zip the contents of the dist folder

    - name: Archive the build
      uses: actions/upload-artifact@v4
      with:
        name: executable
        path: dist\executables.zip  # Upload the zipped file
